# Generated by Django 4.0.3 on 2022-06-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_id', models.IntegerField(null=True)),
                ('dish_name', models.CharField(max_length=50)),
                ('dish_price', models.CharField(max_length=10)),
                ('dish_category', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
