# Generated by Django 4.0.3 on 2022-06-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(default=' ', max_length=100)),
                ('phoneno', models.IntegerField(default=0, max_length=10)),
                ('orderdate', models.CharField(default=' ', max_length=50)),
                ('sheduletime', models.CharField(default=' ', max_length=50)),
                ('dish_list', models.CharField(default=' ', max_length=1000)),
                ('quantity_list', models.CharField(default=' ', max_length=1000)),
                ('price_list', models.CharField(default=' ', max_length=1000)),
                ('members', models.IntegerField(default=0, max_length=2)),
                ('total', models.IntegerField(default=0, max_length=10)),
            ],
        ),
    ]
